In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.backends.backend_pdf
import matplotlib as mpl
import copy
from matplotlib.colors import LinearSegmentedColormap, ListedColormap

In [2]:
cytoPath_read = "/home/androx/Documents/trabalho/citobands/cytobandFiltered_processed_str_dr.txt"


cytobands_df = pd.read_csv(cytoPath_read, sep="\t")#, header=None))

cytobands_df

,Chromossome,First_index,Last_index,Citoband,Unkown,Size,STR_Density,DR_density
0,chr1,0,2299999,p36.33,gneg,2299999,0.088,0.326
1,chr1,2300000,5299999,p36.32,gpos25,2999999,0.084,0.282
2,chr1,5300000,7099999,p36.31,gneg,1799999,0.056,0.275
3,chr1,7100000,9099999,p36.23,gpos25,1999999,0.049,0.405
4,chr1,9100000,12499999,p36.22,gneg,3399999,0.056,0.404
...,...,...,...,...,...,...,...,...
858,chrY,12400000,17099999,q11.221,gpos50,4699999,0.037,0.015
859,chrY,17100000,19599999,q11.222,gneg,2499999,0.062,0.013
860,chrY,19600000,23799999,q11.223,gpos50,4199999,0.082,0.006
861,chrY,23800000,26599999,q11.23,gneg,2799999,0.026,0.002
862,chrY,26600000,57227414,q12,gvar,30627414,0.006,0.001

In [4]:
cytobands_df2 =  cytobands_df.sort_values(['Chromossome'])
cytobands_df2

,Chromossome,First_index,Last_index,Citoband,Unkown,Size,STR_Density,DR_density
0,chr1,0,2299999,p36.33,gneg,2299999,0.088,0.326
34,chr1,123400000,125099999,q11,acen,1699999,0.982,0.000
35,chr1,125100000,143199999,q12,gvar,18099999,0.003,0.000
36,chr1,143200000,147499999,q21.1,gneg,4299999,0.092,0.190
37,chr1,147500000,150599999,q21.2,gpos50,3099999,0.043,0.291
...,...,...,...,...,...,...,...,...
854,chrY,600000,10299999,p11.2,gneg,9699999,0.078,0.017
853,chrY,300000,599999,p11.31,gpos50,299999,0.326,0.024
861,chrY,23800000,26599999,q11.23,gneg,2799999,0.026,0.002
856,chrY,10400000,10599999,q11.1,acen,199999,0.750,0.000
862,chrY,26600000,57227414,q12,gvar,30627414,0.006,0.001

In [7]:
cytobands_df2["Chromossome"][100]

'chr10'