In [1]:
import pandas as pd
import numpy as np
import copy

In [2]:
tanscripts_read= "/home/androx/Documents/trabalho/datasets/Disease_genes/mane/Homo_sapiens.GRCh38.112.chr.gff3"
tanscripts_df = pd.read_csv(tanscripts_read, sep="\t", header=None)

tanscripts_df

,0,1,2,3,4,5,6,7,8
0,1,GRCh38,chromosome,1.0,248956422.0,.,.,.,"ID=chromosome:1;Alias=CM000663.2,chr1,NC_00000..."
1,1,.,biological_region,10469.0,11240.0,1.3e+03,.,.,external_name=oe %3D 0.79;logic_name=cpg
2,1,.,biological_region,10650.0,10657.0,0.999,+,.,logic_name=eponine
3,1,.,biological_region,10655.0,10657.0,0.999,-,.,logic_name=eponine
4,1,.,biological_region,10678.0,10687.0,0.999,+,.,logic_name=eponine
...,...,...,...,...,...,...,...,...,...
3516515,Y,.,biological_region,57215804.0,57215813.0,0.999,-,.,logic_name=eponine
3516516,Y,.,biological_region,57215832.0,57215840.0,0.999,+,.,logic_name=eponine
3516517,Y,.,biological_region,57215833.0,57215842.0,0.999,-,.,logic_name=eponine
3516518,Y,.,biological_region,57215862.0,57215867.0,0.999,+,.,logic_name=eponine
3516519,Y,.,biological_region,57215862.0,57215870.0,0.999,-,.,logic_name=eponine

In [3]:
tanscripts_df = tanscripts_df.rename(columns={0: 'Chr', 1: 'Genome', 2: 'Type', 3: 'First_index', 4: 'Last_index', 5: 'Value', 6: 'Signal', 7: 'Unknown', 8: 'Identifiers'})
tanscripts_df

,Chr,Genome,Type,First_index,Last_index,Value,Signal,Unknown,Identifiers
0,1,GRCh38,chromosome,1.0,248956422.0,.,.,.,"ID=chromosome:1;Alias=CM000663.2,chr1,NC_00000..."
1,1,.,biological_region,10469.0,11240.0,1.3e+03,.,.,external_name=oe %3D 0.79;logic_name=cpg
2,1,.,biological_region,10650.0,10657.0,0.999,+,.,logic_name=eponine
3,1,.,biological_region,10655.0,10657.0,0.999,-,.,logic_name=eponine
4,1,.,biological_region,10678.0,10687.0,0.999,+,.,logic_name=eponine
...,...,...,...,...,...,...,...,...,...
3516515,Y,.,biological_region,57215804.0,57215813.0,0.999,-,.,logic_name=eponine
3516516,Y,.,biological_region,57215832.0,57215840.0,0.999,+,.,logic_name=eponine
3516517,Y,.,biological_region,57215833.0,57215842.0,0.999,-,.,logic_name=eponine
3516518,Y,.,biological_region,57215862.0,57215867.0,0.999,+,.,logic_name=eponine
3516519,Y,.,biological_region,57215862.0,57215870.0,0.999,-,.,logic_name=eponine

In [4]:
tanscripts_df['Type'].unique()

array(['chromosome', 'biological_region', 'ncRNA_gene', 'lnc_RNA', 'exon',
       nan, 'pseudogene', 'pseudogenic_transcript', 'miRNA', 'gene',
       'mRNA', 'five_prime_UTR', 'CDS', 'three_prime_UTR', 'snRNA',
       'transcript', 'unconfirmed_transcript', 'snoRNA', 'scRNA', 'rRNA',
       'processed_transcript', 'V_gene_segment', 'D_gene_segment',
       'J_gene_segment', 'C_gene_segment', 'tRNA'], dtype=object)

In [5]:
chromosmes = tanscripts_df.loc[tanscripts_df['Type'] == "chromosome"]
chromosmes

,Chr,Genome,Type,First_index,Last_index,Value,Signal,Unknown,Identifiers
0,1,GRCh38,chromosome,1.0,248956422.0,.,.,.,"ID=chromosome:1;Alias=CM000663.2,chr1,NC_00000..."
328201,10,GRCh38,chromosome,1.0,133797422.0,.,.,.,"ID=chromosome:10;Alias=CM000672.2,chr10,NC_000..."
467767,11,GRCh38,chromosome,1.0,135086622.0,.,.,.,"ID=chromosome:11;Alias=CM000673.2,chr11,NC_000..."
673000,12,GRCh38,chromosome,1.0,133275309.0,.,.,.,"ID=chromosome:12;Alias=CM000674.2,chr12,NC_000..."
862634,13,GRCh38,chromosome,1.0,114364328.0,.,.,.,"ID=chromosome:13;Alias=CM000675.2,chr13,NC_000..."
924501,14,GRCh38,chromosome,1.0,107043718.0,.,.,.,"ID=chromosome:14;Alias=CM000676.2,chr14,NC_000..."
1048326,15,GRCh38,chromosome,1.0,101991189.0,.,.,.,"ID=chromosome:15;Alias=CM000677.2,chr15,NC_000..."
1171301,16,GRCh38,chromosome,1.0,90338345.0,.,.,.,"ID=chromosome:16;Alias=CM000678.2,chr16,NC_000..."
1329042,17,GRCh38,chromosome,1.0,83257441.0,.,.,.,"ID=chromosome:17;Alias=CM000679.2,chr17,NC_000..."
1536644,18,GRCh38,chromosome,1.0,80373285.0,.,.,.,"ID=chromosome:18;Alias=CM000680.2,chr18,NC_000..."
1598313,19,GRCh38,chromosome,1.0,58617616.0,.,.,.,"ID=chromosome:19;Alias=CM000681.2,chr19,NC_000..."
1791801,2,GRCh38,chromosome,1.0,242193529.0,.,.,.,"ID=chromosome:2;Alias=CM000664.2,chr2,NC_00000..."
2063156,20,GRCh38,chromosome,1.0,64444167.0,.,.,.,"ID=chromosome:20;Alias=CM000682.2,chr20,NC_000..."
2145930,21,GRCh38,chromosome,1.0,46709983.0,.,.,.,"ID=chromosome:21;Alias=CM000683.2,chr21,NC_000..."
2186784,22,GRCh38,chromosome,1.0,50818468.0,.,.,.,"ID=chromosome:22;Alias=CM000684.2,chr22,NC_000..."
2261287,3,GRCh38,chromosome,1.0,198295559.0,.,.,.,"ID=chromosome:3;Alias=CM000665.2,chr3,NC_00000..."
2484781,4,GRCh38,chromosome,1.0,190214555.0,.,.,.,"ID=chromosome:4;Alias=CM000666.2,chr4,NC_00000..."
2628956,5,GRCh38,chromosome,1.0,181538259.0,.,.,.,"ID=chromosome:5;Alias=CM000667.2,chr5,NC_00000..."
2786252,6,GRCh38,chromosome,1.0,170805979.0,.,.,.,"ID=chromosome:6;Alias=CM000668.2,chr6,NC_00000..."
2952608,7,GRCh38,chromosome,1.0,159345973.0,.,.,.,"ID=chromosome:7;Alias=CM000669.2,chr7,NC_00000..."
3120542,8,GRCh38,chromosome,1.0,145138636.0,.,.,.,"ID=chromosome:8;Alias=CM000670.2,chr8,NC_00000..."
3248106,9,GRCh38,chromosome,1.0,138394717.0,.,.,.,"ID=chromosome:9;Alias=CM000671.2,chr9,NC_00000..."
3384196,MT,GRCh38,chromosome,1.0,16569.0,.,.,.,"ID=chromosome:MT;Alias=chrM,J01415.2,NC_012920.1"
3384360,X,GRCh38,chromosome,1.0,156040895.0,.,.,.,"ID=chromosome:X;Alias=CM000685.2,chrX,NC_00002..."
3505822,Y,GRCh38,chromosome,1.0,57227415.0,.,.,.,"ID=chromosome:Y;Alias=CM000686.2,chrY,NC_00002..."

In [6]:
CDSs = tanscripts_df.loc[tanscripts_df['Type'] == "CDS"]
CDSs

,Chr,Genome,Type,First_index,Last_index,Value,Signal,Unknown,Identifiers
99,1,havana,CDS,65565.0,65573.0,.,+,0,ID=CDS:ENSP00000493376;Parent=transcript:ENST0...
100,1,havana,CDS,69037.0,70008.0,.,+,0,ID=CDS:ENSP00000493376;Parent=transcript:ENST0...
398,1,ensembl_havana,CDS,450740.0,451678.0,.,-,0,ID=CDS:ENSP00000409316;Parent=transcript:ENST0...
544,1,ensembl_havana,CDS,685716.0,686654.0,.,-,0,ID=CDS:ENSP00000329982;Parent=transcript:ENST0...
1165,1,havana,CDS,924432.0,924948.0,.,+,0,ID=CDS:ENSP00000478421;Parent=transcript:ENST0...
...,...,...,...,...,...,...,...,...,...
3516411,Y,havana,CDS,57209532.0,57209733.0,.,+,0,ID=CDS:ENSP00000518618;Parent=transcript:ENST0...
3516413,Y,havana,CDS,57209822.0,57209980.0,.,+,2,ID=CDS:ENSP00000518618;Parent=transcript:ENST0...
3516415,Y,havana,CDS,57210640.0,57210792.0,.,+,2,ID=CDS:ENSP00000518618;Parent=transcript:ENST0...
3516417,Y,havana,CDS,57211552.0,57211620.0,.,+,2,ID=CDS:ENSP00000518618;Parent=transcript:ENST0...
3516419,Y,havana,CDS,57211761.0,57211894.0,.,+,2,ID=CDS:ENSP00000518618;Parent=transcript:ENST0...

In [ ]:
UTR5 = tanscripts_df.loc[tanscripts_df['Type'] == "three_prime_UTR"]
UTR5

In [ ]:
UTR3 = tanscripts_df.loc[tanscripts_df['Type'] == "five_prime_UTR"]
UTR3

In [ ]:
def calc_avrg(df):
    total_length = 0
    for row in df.index:
        length = df["Last_index"][row] - df["First_index"][row]
        total_length += length
    average = total_length/len(df)